### ISSUE TITLE
generic_thermostat Unrecognized operation mode: Heat

### ISSUE THREAD

**Issue by phsdv** [efficiosoft/hass-apps#10]
Since I added a generic Thermostat I get the following errors in HA:
```
2018-03-16 07:15:01 ERROR (MainThread) [homeassistant.components.climate.generic_thermostat] Unrecognized operation mode: Heat
```
For me it is a cosmetic error, as my heater still works. 
I believe the generic thermostat expects a full lower case "heat"

I am testing the following change: 
line 146 in hass_apps/heaty/config.py from:
```
 vol.Optional("opmode_heat", default="Heat"): str,
```
to:
```
 vol.Optional("opmode_heat", default="heat"): str,
```
I will report the outcome here.
[edit]
just realized that this is just a default value, so I really should change this in the yaml file
[/edit]

**Comment by efficiosoft** [comment]
Hi,

Yes, I was really smiling when I saw you changing the hard-coded default value of a setting rather than the value of that setting itself. :-)

Have fun with Heaty.

Best regards
Robert
