### ISSUE TITLE
[heaty] Target temperature reverting when manually changed

### ISSUE THREAD

**Issue by stefans2904** [efficiosoft/hass-apps#19]
Hi! I have an issue with the Heaty app (version 0.16.0). I'm not sure if it's a configuration issue or working as designed, but when I set a temperature manually from Home Assistant, Heaty is reverting this back to the temperature set in the schedule. I'm using the Generic Thermostat in Home Assistant.

This is what happens in Heaty when I set the temperature in Home Assistant tot 21 degrees while the schedule is active for 20 degrees:

```
2018-09-27 17:15:15.752282 INFO heaty_minimal: --> [R:huis] [T:climate.verwarming] Received target temperature of 21.0°.
2018-09-27 17:15:15.754841 INFO heaty_minimal: --- [R:huis] Re-scheduling not before 17:15:14 (0:00:00).
2018-09-27 17:15:16.055989 INFO heaty_minimal: <-- [R:huis] Temperature set to 20.0°.  [scheduled]
2018-09-27 17:15:16.067634 INFO heaty_minimal: --> [R:huis] [T:climate.verwarming] Received target temperature of 20.0°.
```

So it reverts to the scheduled temperature. I would like to be able to manually change the temperature from Home Assistant without Heaty reverting it back.

My configuration is as following:

```
heaty_minimal:
  module: hass_apps_loader
  class: HeatyApp
  master_switch: input_boolean.heating_master
  off_temp: 15.0

  rooms:
    huis:
      thermostats:
        climate.verwarming:
        
      schedule:
      - { temp: 20.0, start: "09:00", end: "23:00", weekdays: 1 }
      - { temp: 20.0, start: "17:00", end: "23:00", weekdays: 2-5 }
      - { temp: 20.0, start: "10:00", end: "23:00", weekdays: "6,7" }
      - { temp: 17.0 }
```

**Comment by efficiosoft** [comment]
Hi,

That's indeed a bug. I fixed it in master right now. You may want to use the development version until the fix get's released officially.

Best regards
Robert

**Comment by efficiosoft** [comment]
Ah, and thanks for reporting!
