### ISSUE TITLE
Support for external temperature sensor

### ISSUE THREAD

**Issue by alekslyse** [efficiosoft/hass-apps#28]
Is it possible to use this app with an external temperature sensor to automatically adjust the setpoint? My thermostat does not read correctly the temperature, and rather want to use a zwave temperature sensor to be the goal for the AC instead of the builtin one.

**Comment by alekslyse** [comment]
Maybe something like a dynamic setpoint that adjust the delta automatically. For example if an external sensor (or multiple for avg) is used it use that as the baseline and try as best it can to adjust the AC according to that it slowly on the trend adjust the delta up or down untill the sensor(s) is at the prefered temperature. This could very likely be combined with things like fan speed and direction to automatically keep zones at the correct temperature.

A lot of AC has a very badly placed temperature sensor making its own air affect the reading, so actually having a sensor or avg of multiple would in my view make smart home more useable.

**Comment by efficiosoft** [comment]
But that's not related to scheduling at all. The thermostat is responsible for maintaining the setpoint, however it may do that. Do you know the generic thermostat component in HA? That's a good starting point for building own thermostats from temperature sensor and a switchable heater.

What you can also do is writing a more complex expression for the schedule that outputs a setpoint based on arbitrarily complex criteria, such as your temperature sensor. You'll have to write it yourself, of course.

**Comment by efficiosoft** [comment]
As this is no issue with Schedy, I'll close it now. Feel free to ask if you've got further questions.
