### ISSUE TITLE
[schedy] Changes are propagated to actors in other rooms

### ISSUE THREAD

**Issue by illese** [efficiosoft/hass-apps#31]
It seems that if you have two different rooms in the config with two termostats manual changes are propagated from one to the other nevertheless. Here is the config and the log content
[appdemonlog.txt](https://github.com/efficiosoft/hass-apps/files/2941291/appdemonlog.txt)

config: (saved as text for the simplicity)
[sample_apps -yaml.txt](https://github.com/efficiosoft/hass-apps/files/2941302/sample_apps.-yaml.txt)

**Comment by efficiosoft** [comment]
I'm almost certainly sure that this is a configuration mistake. However, I can't read your configuration if you don't put it into a proper code block.

**Comment by illese** [comment]
Can certainly be.
Full config:
`schedy:  # An arbitrary name for this instance of Schedy,
         # needed e.g. for addressing events to it.
  # Obligatory settings that tell appdaemon where to find the app.
  # You shouldn't need to change these two.
  module: hass_apps_loader
  class: SchedyApp

  # Enable debugging output
  #debug: false
  actor_type: thermostat

  # By default, Schedy tries to restore its previous state at startup
  # from the records stored in Home Assistant. This includes scheduled
  # values, manual adjustments and re-scheduling times - just everything.
  # When this behaviour is not desired, change this setting to true
  # and Schedy will just apply the schedules at startup, no matter what
  # the previous actor states were.
  #reset_at_startup: false


  # If you enable this option, potentially harmful expressions received
  # in schedy_set_value events are evaluated.
  #expressions_from_events: false

  # Here you can define Python modules that should be available
  # inside your expressions. These modules are imported upon Schedy's
  # initialization, hence you have to restart AppDaemon after making
  # changes to these modules.
  expression_modules:
    #math:
    #my_custom_module:
      # Optionally, define an alternative name under which the module
      # should be available.
      #as: alt_name


  # Chose the type of actors that should be controlled by this instance
  # of Schedy.
  # Possible types can be found in the documentation.
  #actor_type: <required>

  # In the following config block, you may define templates with
  # settings that affect multiple actors in your setup. These can then be
  # used as a starting point for the configuration of individual actors.
  # Nested inclusion of templates is possible as well.
  actor_templates:

    # Each template needs to have a name.
    #my_template:

      # Optionally have this template based on another one.
      #template: other_template

      # Actor type-specific settings can be found in the documentation.
      #foo: bar
      #...


  # Add schedule rules you want to have prepended to each room's schedule
  # automatically here.
  schedule_prepend:

  # Add schedule rules you want to have appended to each room's schedule
  # automatically here.
  schedule_append:

  # Optionally, configure schedule snippets (lists of rules) that can
  # be included by expressions dynamically. See the documentation for
  # an example on how to use them.
  schedule_snippets:

    #summer:
    #- ...


  # When you use expressions in your schedules that query the state of
  # entities, you should tell Schedy which entities the schedules depend
  # on. It can then watch for state changes of these and re-evaluate
  # schedules automatically.
  # Note: Entities listed here trigger a re-evaluation in all rooms. For
  # entities only used in the schedules of particular rooms, use the
  # per-room watched_entities list.
  watched_entities:

    # Each entry has to be a string consisting of up to three
    # colon-separated parts:
    #
    # 1. The id of the entity to watch. This is mandatory.
    # 2. Which attributes to watch for changes of, either a single
    #    attribute or a comma-separated list.
    #    The special value "all" listens for changes of any attribute. Try
    #    to avoid this whenever possible as it can increase the load
    #    significantly.
    #    Default: "state"
    # 3. The re-evaluation mode as known from the schedy_reevaluate event.
    #    The special mode "ignore" causes no re-evaluation, it just
    #    suppresses the warnings generated when the entity is queried from
    #    an expression.
    #    Default: "reevaluate"
    #
    # Examples:
    # - "binary_sensor.motion"
    # - "binary_sensor.motion:all"
    # - "binary_sensor.motion::reset"
    # - "binary_sensor.motion:state,other_attribute:reset"
    # - "binary_sensor.motion:all:ignore"


  # Configure your rooms here.
  rooms:
   ritaszoba:
    
      # All actors of this room go here.
    actors:
     climate.ritatermosztat:
 
    schedule:
     - v: 21.5
       start: "05:30"
       end: "08:00"
       name: hetkoznap_reggel
       weekdays: 1-5

     - v: 21.5
       start: "16:30"
       end: "23:00"
       name: hetkoznap_este
       weekdays: 1-5

     - v: 21.5
       start: "07:30"
       end: "23:00"
       name: hetvege
       weekdays: 6-7
     

     - v: 22.3
       start: "10:45"
       end: "10:47"
       name: dsdal
       weekdays: 1-5

     - v: 15
      #- ...

   nappali:
    
      # All actors of this room go here.
    actors:
     climate.nappalitermosztat:
     climate.ritatermosztat:
 
    schedule:
     - v: 21.5
       start: "05:30"
       end: "08:00"
       name: hetkoznap_reggel
       weekdays: 1-5

     - v: 21.5
       start: "16:30"
       end: "23:00"
       name: hetkoznap_este
       weekdays: 1-5

     - v: 21.5
       start: "07:30"
       end: "23:00"
       name: hetvege
       weekdays: 6-7
     
     - v: 24.5
       start: "09:20"
       end: "09:21"
       name: dsdl
       weekdays: 1-5
     - v: 15


      # The same as the global watched_entities above, but these only
      #  trigger a re-evaluation for this particular room.
    #watched_entities:
      #- ...


    # Configure statistical parameters to be collected.
    #statistics:

      # Pick an arbitrary name for the parameter instance.
      #some_name:
        # The type of parameter as found in the actor'S documentation.
        #type: <required>
        # More parameter-specific settings ...

      # More parameter instances ...`

**Comment by efficiosoft** [comment]
And, I need a full log with ``debug: true`` from the startup of AppDaemon on.

**Comment by efficiosoft** [comment]
Please, delete your last post and edit the first one instead. Use the Preview function to check your markup is working before posting.

**Comment by illese** [comment]
Edited. Sry my default tool is VSTS not github.

**Comment by efficiosoft** [comment]
That log isn't complete. It starts somewhere half way through the initialization.

Second, the indentation of your config is really weird. YAML depends on indentation to function correctly, and to keep it maintainable, you should really make the indentation unique, preferably using at least 2 spaces per indentation level.

**Comment by illese** [comment]
Config error. Found. Close the bug that is the issue...

   nappali:
    
      # All actors of this room go here.
    actors:
     climate.nappalitermosztat:
     climate.ritatermosztat:

**Comment by efficiosoft** [comment]
Sure, but that wasn't the config you posted.

**Comment by illese** [comment]
Indeed, very strange, some versioning issue on my system (copied from a mirror dir that should have been exactly the same). But but anyhow sorry for the false bug, great program.
