### ISSUE TITLE
[schedy]Bug in schedule.next_results

### ISSUE THREAD

**Issue by flotre** [efficiosoft/hass-apps#33]
Hello,

I think there is an issue in schedule.next_results
```
while when and (not end or end > when):
            result = schedule.evaluate(self._room, when)
            if result and result != last_result:
                yield when, result
                last_result = result
            when = schedule.get_next_scheduling_datetime(when)
```
in my configuration :
start=now
end = now + 3 hours
result = None
if schedule.get_next_scheduling_datetime return always the same value

schedule being evaluated:
- x: "float(state('input_number.mode_confort'))"
        start: "20:00"
        end: "08:00"
        name: Nuit
      - x: "float(state('input_number.mode_confort'))"
        start: "13:00"
        end: "16:00"
        name: Sieste
        weekdays: 6,7

**Comment by efficiosoft** [comment]
Hi,

Thanks for reporting. I'll have a look into this soon.

Just for completeness: What were the values of these input_numbers?

Best regards
Robert

**Comment by efficiosoft** [comment]
And please re-test with the latest development version (state of the master branch).

**Comment by flotre** [comment]
latest development version works fine since this morning.
thank you for the fix

**Comment by efficiosoft** [comment]
Brilliant, it'll go into the next release.
