### ISSUE TITLE
[schedy] Compatibility with new climate API of Home Assistant 0.96

### ISSUE THREAD

**Issue by asjmcguire** [efficiosoft/hass-apps#34]
Hi,
I want to upgrade to v0.96 but there has been major cleanup of the climate components as part of this release. 
Will overriding opmode_on_service from climate/set_operation_mode to climate/set_hvac_mode and opmode_on_service_attr from operation_mode to hvac_mode be sufficient to keep the app running after upgrading - until the code is changed to accommodate the climate changes in v0.96?

**Comment by efficiosoft** [comment]
I wasn’t aware of these changes yet. Are you still using  Heaty? If yes, you’re really supposed to switch over to  Schedy now. I will investigate this tonight and release a fix for  Schedy, but not for Heaty.

Best regards
Robert

**Comment by asjmcguire** [comment]
Yes, but I was checking the documentation and code commits or Schedy before I opened this issue because it's affected too. The information here https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html is now live in v0.96

**Comment by efficiosoft** [comment]
This issue has been fixed in the latest release.

Thanks for reporting.
