### ISSUE TITLE
cached install when Internet down

### ISSUE THREAD

**Issue by bejam** [efficiosoft/hass-apps#38]
Hi, Loving schedy. This may be a bit of a noob question. I am using the automated install under hassio. It is all working fine - my config has 'hass-apps' in the appdaemon config and I have set requirements.txt to the latest version (hass-apps==0.20190720.0). My issue is that when the Internet is down and app-daemon is restarted, it fails and exits. This is not ideal when trying to ensure the heating works offline. Is there a way for it to check for a cached version from the info in requirements.txt and use that if there is no Internet connection? Or I have to do a manual install... which  means more config and upgrade difficulty.

**Comment by efficiosoft** [comment]
Hi,

I know that this is an issue, but IMHO this is something to be addressed by the hassio add-on developers, as it's not related to hass-apps specifically. Everything you have in the `python_packages` setting suffers from this. It would be great if you could report the problem to the add-on maintainers. I'm not using HassOS myself and thus can't do any sensible testing in that regard. You can of course mention me in the issue if you like.

Best regards
Robert
