### ISSUE TITLE
[schedy] OVERLAY marker isn't working

### ISSUE THREAD

**Issue by morrydavis** [efficiosoft/hass-apps#49]
I added the property to my entites in customize.yaml but not sure how the mark('off',mark.overlais) is supposed to work but not turning off heater if window is open
here is what I added to schedule_prepend
 - x: "Mark(OFF, Mark.OVERLAY) if not is_empty(filter_entities('binary_sensor', window_room=living, state='on')) else Next()"

**Comment by efficiosoft** [comment]
The OVERLAY marker works well. However, without any log of Schedy I can't tell you anything. This is no bug BTW, so please ask in the [Schedy thread in the HA community forums](https://community.home-assistant.io/t/heaty-will-die-schedy-be-born/71276). I'm closing this.

**Comment by morrydavis** [comment]
All is good I got it working
